a = "lol"
b = " ".join([a, a, a, a, a, a, a, a, a, a])
c = " ".join([b, b, b, b, b, b, b, b, b, b])
d = " ".join([c, c, c, c, c, c, c, c, c, c])
e = " ".join([d, d, d, d, d, d, d, d, d, d])
f = " ".join([e, e, e, e, e, e, e, e, e, e])
g = " ".join([f, f, f, f, f, f, f, f, f, f])
h = " ".join([g, g, g, g, g, g, g, g, g, g])
i = " ".join([h, h, h, h, h, h, h, h, h, h])
j = " ".join([i, i, i, i, i, i, i, i, i, i])
print(j)
